#!/bin/bash

# List EC2 instances
echo "Listing EC2 Instances:"
aws ec2 describe-instances --query 'Reservations[*].Instances[*].{ID:InstanceId,Type:InstanceType,State:State.Name}' --output table

# List S3 buckets
echo "Listing S3 Buckets:"
aws s3 ls

# List Lambda functions
echo "Listing Lambda Functions:"
aws lambda list-functions --query 'Functions[*].{FunctionName:FunctionName,Runtime:Runtime}' --output table

